exports.KEYS = {};
exports.KEYS.LOGINSTATUS = "LOGINSTATUS";
exports.KEYS.TUTORPROFILEUPDATE = "TUTORPROFILEUPDATE";
exports.KEYS.USERTYPE = "USERTYPE";
exports.KEYS.REGISTRATIONCOMPLETE ="REGISTRATIONCOMPLETE";
exports.KEYS.USER = "USER";
exports.KEYS.FIRST_TIME_PROFILE_NAVIGATOR_OPEN = "FIRST_TIME_PROFILE_NAVIGATOR_OPEN";
