exports.KEYS = {};
exports.KEYS.LOGINSTATUS = "LOGINSTATUS";
exports.KEYS.TUTORPROFILEUPDATE = "TUTORPROFILEUPDATE";
exports.KEYS.USERTYPE = "USERTYPE";
exports.KEYS.REGISTRATIONCOMPLETE ="REGISTRATIONCOMPLETE";
exports.KEYS.USER = "USER";
